

{{- if and .Values.openagenticProxy.enabled (or (.Values.openagenticProxy.podDisruptionBudget).enabled (.Values.openagenticProxy.hpa).enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openagentic.fullname" . }}-openagentic-proxy
  labels:
    {{- include "openagentic.labels" . | nindent 4 }}
    app.kubernetes.io/component: openagentic-proxy
spec:
  {{- if and (.Values.openagenticProxy.podDisruptionBudget).minAvailable }}
  minAvailable: {{ .Values.openagenticProxy.podDisruptionBudget.minAvailable }}
  {{- else if and (.Values.openagenticProxy.podDisruptionBudget).maxUnavailable }}
  maxUnavailable: {{ .Values.openagenticProxy.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "openagentic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: openagentic-proxy
{{- end }}
