

{{- if and .Values.ollama.enabled (or (.Values.ollama.podDisruptionBudget).enabled (.Values.ollama.autoscaling).enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openagentic.fullname" . }}-ollama
  labels:
    {{- include "openagentic.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  {{- if and (.Values.ollama.podDisruptionBudget).minAvailable }}
  minAvailable: {{ .Values.ollama.podDisruptionBudget.minAvailable }}
  {{- else if and (.Values.ollama.podDisruptionBudget).maxUnavailable }}
  maxUnavailable: {{ .Values.ollama.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "openagentic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ollama
{{- end }}
