

{{- if and .Values.api.enabled (or (.Values.api.podDisruptionBudget).enabled (.Values.api.autoscaling).enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openagentic.fullname" . }}-api
  labels:
    {{- include "openagentic.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if and (.Values.api.podDisruptionBudget).minAvailable }}
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  {{- else if and (.Values.api.podDisruptionBudget).maxUnavailable }}
  maxUnavailable: {{ .Values.api.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "openagentic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
