/**
 * Copyright (c) 2024-2026 AgenticWork LLC. All rights reserved.
 *
 * ADMIN_INV — the per-leaf option-spec inventory SoT.
 *
 * Every leaf keeps a two-part contract (blueprint §1): its rich/generic
 * body PLUS an "All configurable options" inventory table below it. This
 * file is the faithful port of the mock's `INV` map — one entry per leaf,
 * each a list of [label, type, detail] rows. `OptionSpec` (the primitive)
 * renders these via TYPE_META.
 *
 * This is UI-local STATIC SPEC; the live "control" wires to the same
 * mutation endpoints listed in the blueprint §2 wiring table. The
 * inventory is seeded here in Phase 0 and filled / refined per-page in
 * later phases.
 *
 * Keyed by canonical leaf id (the contract key — blueprint §0).
 */
import type { OptionSpecInventory, OptionSpecRow } from './types'

/** Build a leaf inventory entry. */
function inv(domain: string, opts: OptionSpecRow[]): OptionSpecInventory {
  return { domain, opts }
}

export const ADMIN_INV: Record<string, OptionSpecInventory> = {
  /* ---- Models & Providers ---- */
  providers: inv('Models&Providers', [
    ['PageHead title + meta', 'kpi', "Title 'Providers'; meta '{total} registered · {healthy} healthy · {modelCount} models · auto-refresh 30s'"],
    ['refresh', 'action-button', 'ghost btn; refetches useLlmProviders + useProviderHealth'],
    ['+ add provider', 'action-button', 'primary btn; opens ProviderModal in add mode'],
    ['Subtabs', 'tab', 'overview · health · models · performance · cost · activity (6 tabs)'],
    ['degraded banner', 'badge', 'warn Banner listing degraded provider display names; error Banner on load fail'],
    ['KPI: total providers', 'kpi', 'value=total; sub "{disabled} disabled"'],
    ['KPI: healthy', 'kpi', 'value "{healthy}/{total}"; tone warn if degraded'],
    ['KPI: models registered', 'kpi', 'value=modelCount; sub "across {total} providers"'],
    ['KPI: spend (24h)', 'kpi', 'value=fmtUsd(summary.totalCost); from useDashboardMetrics(24h)'],
    ['Overview: search', 'text-input', 'FilterRow placeholder "provider, type, endpoint…"; URL key q'],
    ['Overview: status filter chips', 'select', 'chips all/healthy/degraded/disabled with live counts; URL key status'],
    ['Overview table', 'table', 'Provider | Tier(P0-P5) | Status | Models | Last Check | Enabled(Toggle) | actions. Double-click → detail; dimmed if disabled'],
    ['Overview: bulk action bar', 'action-button', 'row selection → enable / disable / delete(destructive); fans PUT/DELETE per row'],
    ['Overview: empty state', 'list', 'EmptyState "No providers configured" CTA "+ add provider"'],
    ['Health pane: Provider Health table', 'table', 'Provider | Status(StatusDot) | Endpoint(mono) | Last Check | Last Error'],
    ['Health pane: API Requests chart', 'chart', 'area MetricChart of timeSeries.apiRequests (24h) as provider load proxy'],
    ['Models pane table', 'table', 'flattens all provider models[]; Model | Provider | Capabilities | Max Tokens | Enabled'],
    ['Performance sub-tab', 'tab', 'renders PerformancePane (same as llm-performance leaf)'],
    ['Cost pane: Spend by Provider chart', 'chart', 'stacked area usd, top-5 providers from costByModel'],
    ['Cost pane: Provider Cost Totals table', 'table', 'Provider | Cost(24h) ranked desc'],
    ['Activity pane table', 'table', 'scoped audit resourceType=LLMProvider limit 200; When | Actor | Action | Resource | Result'],
    ['Detail SidePanel tabs', 'side-panel', 'overview·models·auth·logs·cost; headActions re-probe + edit'],
    ['Detail overview tab', 'form', 'status, last checked, last error; Type, Region, Endpoint, Tier, Models registered'],
    ['Detail models tab', 'table', 'Model | Capabilities | Max Tokens'],
    ['Detail auth tab', 'form', 'Auth type, Has API key(yes/no), Has credentials(yes/no)'],
    ['Detail logs tab', 'table', 'scoped audit by provider name+id; When|Actor|Action'],
    ['Detail cost tab', 'table', '24h total + per-model rows for this provider'],
    ['ProviderModal: Name', 'text-input', 'lowercase kebab id; /^[a-z0-9][a-z0-9-]*$/; disabled on edit'],
    ['ProviderModal: Display name', 'text-input', 'required; shown in operator UI'],
    ['ProviderModal: Provider type', 'select', 'azure-openai, azure-ai-foundry, vertex-ai, aws-bedrock, ollama, anthropic, openai; disabled on edit'],
    ['ProviderModal: Priority', 'number-input', '0–100, lower=preferred; default 50'],
    ['ProviderModal: Enabled', 'toggle', 'checkbox; default true'],
    ['ProviderModal: Description', 'text-input', 'optional textarea notes'],
    ['ProviderModal: Auth mode', 'select', 'azure-* only: api-key | entra-id; swaps auth field set'],
    ['ProviderModal: auth fields (azure-openai)', 'form', 'api-key: Endpoint, API Key, Deployment, API Version. entra-id: Endpoint, Tenant ID, Client ID, Client Secret, Deployment, API Version'],
    ['ProviderModal: auth fields (azure-ai-foundry)', 'form', 'api-key: Endpoint, API Key, Deployment(model-router), API Version. entra-id: +Tenant/Client/Secret'],
    ['ProviderModal: auth fields (vertex-ai)', 'form', 'GCP Project ID(req), Region(us-central1), Service Account JSON(textarea)'],
    ['ProviderModal: auth fields (aws-bedrock)', 'form', 'AWS Region(req us-east-1), Access Key ID(password), Secret Access Key(password)'],
    ['ProviderModal: auth fields (ollama)', 'form', 'Endpoint URL(req http://ollama:11434)'],
    ['ProviderModal: auth fields (anthropic)', 'form', 'API Key(password req), Base URL(https://api.anthropic.com)'],
    ['ProviderModal: auth fields (openai)', 'form', 'API Key(password req), Base URL(https://api.openai.com/v1)'],
    ['ProviderModal: AIF providerConfig', 'form', 'useUnifiedEndpoint(toggle false), contentFilterLevel(low/medium/high, def medium)'],
    ['ProviderModal: vertex-ai providerConfig', 'form', 'globalEndpoint(toggle false), safetySettings(default/block-low/block-high/block-none)'],
    ['ProviderModal: aws-bedrock providerConfig', 'form', 'endpoint(VPC/FIPS override), crossRegionInference(toggle true), guardrailsId(ARN), invocationLogging(toggle false)'],
    ['ProviderModal: ollama providerConfig', 'form', 'numGpu(0-999 def 0), numThread(0-256 def 0), autoPullModels(toggle false)'],
    ['ProviderModal: anthropic providerConfig', 'form', 'promptCachingBeta(toggle true), extendedThinkingDefault(off/low/medium/high)'],
    ['ProviderModal: openai providerConfig', 'form', 'organizationId(org-…), projectId(proj_…)'],
    ['ProviderModal: derived origin', 'form', 'deriveOrigin auto-computes FedRAMP per-type origin fields → providerConfig.origin'],
    ['ProviderModal: save (optimistic concurrency)', 'action-button', 'create POST or edit PUT /:id with version token; 409 on concurrent edit'],
    ['Mutations', 'action-button', 'create POST; edit/toggle PUT /:id; delete DELETE /:id?force=true; health re-probe POST /:name/test'],
  ]),
  'default-models': inv('Models&Providers', [
    ['PageHead title + meta', 'kpi', "Title 'Default Models'; meta '{configured}/{totalRoles} roles · {modelCount} models · auto-refresh 60s'"],
    ['refresh', 'action-button', 'ghost; refetch defaults + registry'],
    ['reset', 'action-button', 'ghost; confirm → POST default-models/reset (overwrites all to helm seed)'],
    ['+ assign role', 'action-button', 'primary; opens RoleAssignModal in add mode'],
    ['Subtabs', 'tab', 'roles · by use case · conflicts'],
    ['error/stale banner', 'badge', 'err on load fail; warn "{stale} roles pinned to missing model"'],
    ['KPI: roles configured', 'kpi', '"{configured}/{totalRoles}"; tone warn if stale'],
    ['KPI: models in registry', 'kpi', 'value=modelCount; sub "enabled only"'],
    ['KPI: total req (24h)', 'kpi', 'sum role usage.count'],
    ['KPI: total cost (24h)', 'kpi', 'sum role usage.cost'],
    ['Roles pane: orphaned banner', 'badge', 'err if any role pinned to deleted model — falls to chat-default'],
    ['Roles pane table', 'table', '5 roles; Role | Assigned Model(red if stale) | Provider | Tier | FCA | Cost/1k | Req(24h) | Tokens'],
    ['By Use Case pane', 'list', '3-col card grid; useCase, role, StatusDot, tier, model, provider, req·24h, description'],
    ['Conflicts pane table', 'table', 'stale only; Role | Pinned Model | Reason. empty "no conflicts detected"'],
    ['Detail SidePanel tabs', 'side-panel', 'overview · alternates · usage; headActions edit'],
    ['Detail overview tab', 'form', 'Use case, Description, Applied to; Assigned, Provider, Tier, FCA, Cost/1k, Stale'],
    ['Detail alternates tab', 'table', 'sim ranked (0.5×cost+0.5×quality); Model|Provider|FCA|Cost/1M|Sim Score|switch-to; top 20'],
    ['Detail usage tab', 'form', '24h Requests, Tokens, Cost'],
    ['RoleAssignModal: Role select', 'select', 'chat/code/embedding/vision/imageGen; locked when from switch-to/edit'],
    ['RoleAssignModal: Model select', 'select', '— select —, auto · smart-router, then capability-filtered candidates'],
    ['RoleAssignModal: Currently', 'badge', 'shows current assigned model when differs'],
    ['RoleAssignModal: save', 'action-button', 'PUT default-models body {[role]: modelId}'],
    ['Role metadata (5 roles)', 'list', 'chat→ChatCompletionService; code→Agenticode CLI; embedding→UniversalEmbeddingService/Milvus; vision; imageGen→generate_image. AUTO_VALUE=auto'],
  ]),
  'model-management': inv('Models&Providers', [
    ['PageHead title + meta', 'kpi', "Title 'Models'; meta '{total} models · {enabled} enabled · {providers} providers · auto-refresh 60s'"],
    ['refresh', 'action-button', 'ghost; refetch registry+providers'],
    ['refresh from providers', 'action-button', 'POST registry/refresh-all; toasts "scanned N · +X · Y updated · Z errors"'],
    ['+ add model', 'action-button', 'primary; opens ModelBrowseModal (browse provider catalog)'],
    ['Subtabs', 'tab', 'catalog · capabilities · pricing · live usage · playground'],
    ['KPI: models in registry', 'kpi', 'value=total'],
    ['KPI: enabled', 'kpi', '"{enabled}/{total}"; tone warn if 0'],
    ['KPI: providers', 'kpi', 'distinct provider rows count'],
    ['KPI: avg cost / 1M tok', 'kpi', 'avg inputCostPer1k×1000 across enabled priced models'],
    ['Catalog: search', 'text-input', 'FilterRow "model, provider, role…"; URL key q'],
    ['Catalog: status filter chips', 'select', 'all / enabled / disabled (live counts)'],
    ['Catalog: provider filter chips', 'select', 'top-6 providers by model count; URL key provider'],
    ['Catalog: capability filter chips', 'select', 'chat/tools/vision/embed/stream/think/image-gen; URL key cap'],
    ['Catalog: column picker', 'action-button', 'ColumnPicker hidden-cols persisted key model-registry-catalog'],
    ['Catalog table', 'table', 'Model(id+role+cost/1M) | Provider | Tier | Capabilities | Max Tokens | Enabled(Toggle) | actions'],
    ['Catalog: bulk action bar', 'action-button', 'selection → enable/disable/delete; fans PATCH/DELETE /registry/:id'],
    ['Catalog: empty state', 'list', 'EmptyState "No models in registry" CTA "+ add model"'],
    ['Capabilities pane (matrix)', 'table', 'model rows × cap cols (chat/tools/vision/embed/stream/think/image-gen) with ✓/·'],
    ['Pricing pane', 'table', 'sorted by input cost desc; Model | Input·/1M(warn >5×p50) | Output·/1M | Source badge'],
    ['Live usage pane', 'table', 'top-20 by tokens; Model | Req(24h) | Tokens | Cost. window 24h'],
    ['Playground pane', 'form', 'Provider select, Model select, Test Type(chat/streaming/tools), Max Tokens(64-8192), Quick Prompts(5), Clear History, message + Send'],
    ['Detail SidePanel tabs', 'side-panel', 'overview · caps · pricing · usage 24h · logs'],
    ['Detail overview tab', 'form', 'Model id, Registry id, Provider, Role, Family, Tier, Priority; Enabled, Max tokens, FCA, Avg latency'],
    ['Detail caps tab', 'form', 'per-cap yes/no chat/tools/vision/embeddings/streaming/thinking/image generation'],
    ['Detail pricing tab', 'form', 'Cost source, Input·/1M, Output·/1M, Input·/1k, Output·/1k'],
    ['Detail usage tab', 'form', '24h Requests/Tokens/Cost'],
    ['Detail logs tab', 'table', 'scoped audit by model id; When|Actor|Action'],
    ['ModelModal EDIT: Model id / Provider', 'badge', 'immutable mono display'],
    ['ModelModal EDIT: Role', 'select', 'chat/code/embedding/vision/image-generation/reasoning'],
    ['ModelModal EDIT: Enabled', 'toggle', 'checkbox'],
    ['ModelModal EDIT: Max tokens', 'number-input', 'min 1'],
    ['ModelModal EDIT: Temperature', 'number-input', '0-2 step 0.1'],
    ['ModelModal EDIT: Function-calling accuracy', 'number-input', '0-1 step 0.01; drives Router Tuning floor scoring'],
    ['ModelModal EDIT: Pricing override', 'number-input', 'inputCostPer1k / outputCostPer1k (USD/1k step 0.0001)'],
    ['ModelModal EDIT: capability checkboxes', 'toggle', 'Chat/Tools/Vision/Embeddings/Streaming/Thinking; PATCH /registry/:id'],
    ['ModelModal ADD: Provider select', 'select', 'enabled providers only'],
    ['ModelModal ADD: Model id', 'text-input', 'provider-native id req; gpt-4o, claude-sonnet-4-5, gemini-2.5-flash'],
    ['ModelModal ADD: Display name', 'text-input', 'optional defaults to id'],
    ['ModelModal ADD: Role', 'select', 'chat/code/embedding/vision/image-generation/reasoning'],
    ['ModelModal ADD: Max output tokens', 'number-input', 'min 1 default 8192'],
    ['ModelModal ADD: Temperature', 'number-input', '0-2 step 0.1 default 0.7'],
    ['ModelModal ADD: Enabled on add', 'toggle', 'checkbox default true'],
    ['ModelModal ADD: capability checkboxes', 'toggle', 'Chat(true)/Tools/Vision/Embeddings/Streaming(true); POST /:provider/models'],
    ['ModelBrowseModal: Provider select', 'select', 'GET /:name/discover-models (SDK catalog)'],
    ['ModelBrowseModal: search', 'text-input', 'id/name/description/family substring'],
    ['ModelBrowseModal: sort', 'select', 'name | context ↓ | max output ↓ | tier | has chat/tools/vision/thinking/embeddings'],
    ['ModelBrowseModal: capability filter chips', 'select', 'all/chat/tools/vision/thinking/embed/img-gen/stream'],
    ['ModelBrowseModal: discovered table', 'table', 'model id | context | max-out | capabilities | tier | Add btn; MODEL_FAMILY_CONFLICT→force'],
    ['Mutations', 'action-button', 'edit PATCH /registry/:id; delete DELETE ?force=true; add POST; refresh POST refresh-all'],
  ]),
  ollama: inv('Models&Providers', [
    ['Hub PageHead + meta', 'kpi', 'LLMExtrasHubPage; meta StatusDot + "{hosts} hosts · {registryRows} rows · {avgLatency} avg"'],
    ['Hub refresh', 'action-button', 'ghost; refetch ollama+perf+registry'],
    ['Hub Subtabs', 'tab', 'Ollama Hosts · Tiered Function Calling · Performance Metrics'],
    ['Hub KPI: ollama hosts', 'kpi', '"{connected}/{hostCount}"; tone by connected ratio'],
    ['Hub KPI: tier-1 models', 'kpi', 'count priority≤10; sub "routed first"'],
    ['Hub KPI: tier-2 models', 'kpi', 'count priority 11-50; sub "fallback pool"'],
    ['Hub KPI: avg latency (24h)', 'kpi', 'kpis.avgResponseTime; sub "p95 {p95}"'],
    ['pending mutation banner', 'badge', 'info Banner — read-only in v3, use ?v3=0 to write'],
    ['Ollama Hosts table', 'table', 'live probe per row (60s); Status | Host | Models | Running | Chat Model | Pri | Last Sync | Error'],
    ['Ollama empty/error state', 'badge', 'warn on load fail; EmptyInline "no Ollama providers — add type=ollama"'],
    ['READ-ONLY note', 'badge', 'sync/pull/delete/test stubbed; v3 read-only — bounces to v2'],
  ]),
  'tiered-fc': inv('Models&Providers', [
    ['deprecation banner', 'badge', 'warn "Tiered Function Calling replaced by SmartModelRouter FCA scoring (#622)"; old tier selectors no effect'],
    ['where the old settings live now', 'list', 'SectionBar read-only nav → fcaQualityFloor · fcaSimpleToolFloor · fcaComplexToolFloor · fcaDestructiveFloor'],
    ['Router Tuning →', 'action-button', 'ghost btn sets location.hash=#router-tuning (brittle hash-nav)'],
    ['why info banner', 'badge', 'info: V2 routes via FCA not tier buckets; makeDecision() only from admin test endpoint'],
    ['DEPRECATED / dead page', 'badge', 'wired=NO/reporting=NO; cheapModel/balancedModel/premiumModel have no routing effect; GET /tiered-fc still exists'],
  ]),
  'router-tuning': inv('Models&Providers', [
    ['PageHead title + meta', 'kpi', "Title 'Router Tuning'; meta 'scoring weights · {podCount} pods synced · {dirtyCount} unsaved'"],
    ['discard', 'action-button', 'ghost; clears dirty buffer; "discard ({n})"'],
    ['reset', 'action-button', 'ghost; POST router-tuning/reset → defaults'],
    ['save & apply live', 'action-button', 'primary; PUT only dirty keys; disabled if no changes'],
    ['rule-of-thumb banner', 'badge', 'info "0.1 weight change shifts 10–30% of routed traffic"'],
    ['vocabulary legend', 'list', 'FCA = Function-Calling Accuracy; cost = $/1M; latency = p95 ms; quality = BFCL+MMLU+agent blend'],
    ['Scoring formula: costBonusMaxPoints', 'number-input', 'EditableChip; default 25, 0-500'],
    ['Scoring formula: costWeight', 'number-input', 'EditableChip; default 0.5, step 0.05, 0-1'],
    ['Scoring formula: fcaQualityFloor', 'number-input', 'EditableChip; default 0.75, step 0.01, 0-1'],
    ['Scoring formula: fcaQualityMultiplier', 'number-input', 'EditableChip; default 100, 0-1000'],
    ['Scoring formula: qualityWeight', 'number-input', 'EditableChip; default 0.5, step 0.05, 0-1'],
    ['Scoring formula: fcaQualityGatedByComplexity', 'toggle', 'checkbox; default true'],
    ['Scoring formula: latencyBonusMaxPoints', 'number-input', 'EditableChip; default 10, 0-500'],
    ['Scoring formula: toolCallingBonusMaxPoints', 'number-input', 'EditableChip if hasTools; default 50, 0-500'],
    ['Scoring formula: reasoningBonusMaxPoints', 'number-input', 'EditableChip if multi-step; default 30, 0-500'],
    ['Scoring formula: costNormalizationCeiling', 'number-input', 'EditableChip $/1k; default 0.02, step 0.001, 0-1'],
    ['FCA floors (6-tile grid)', 'kpi', 'EditableKpi tiles: fcaChatPoolFloor 0.82 · fcaSimpleToolFloor 0.83 · fcaComplexToolFloor 0.9 · fcaDestructiveFloor 0.93 · fcaInfraOpsFloor 0.85 · fcaComplexityBiasFloor 0.93'],
    ['T3 capability gate: fcaT3Floor', 'number-input', 'EditableKpi warn; default 0.93, step 0.01, 0-1'],
    ['T3 capability gate: contextT3Floor', 'number-input', 'EditableKpi warn; default 200000 tokens, step 1000'],
    ['T3: t3TriggerTaskTypes', 'form', 'JsonTuningEditor — JSON array of TaskType ids'],
    ['T3: capabilityProfileFloors', 'form', 'JsonTuningEditor — JSON map {TaskType: FCA-floor 0-1}'],
    ['T3: capabilityContextFloors', 'form', 'JsonTuningEditor — JSON map {TaskType: context-token-floor}'],
    ['intentClassifierEnabled / intentClassifierModelId', 'form', 'RouterTuningValues (default true; model id from tuning config)'],
    ['Live Scoring Lab: prompt input', 'text-input', 'text + Enter; preset chips easy/medium/hard; "score it →"'],
    ['Live Scoring Lab: analysis line', 'badge', 'hasTools/multiStep/complexReasoning/multiCloud/destructive/complexityBias/est tokens'],
    ['Live Scoring Lab: server pick banner', 'badge', 'info "selectedModelId · tier · resolved by {resolvedBy}"'],
    ['ScoreBreakdownTable', 'table', 'MODEL | TIER | FCA | $/1K | LAT | COST | LAT-PTS | QUAL | TOOLS | REASON | TOTAL | NOTE'],
    ['Recent routing decisions table', 'table', 'last 20; WHEN | TIER | MODEL | RESOLVED BY | FCA | $/1K | LAT | SCORE | PROMPT(80ch)'],
  ]),
  'llm-performance': inv('Models&Providers', [
    ['PerformancePane KPI strip (4)', 'kpi', 'avg ttft · avg response · throughput tok/s · requests (window)'],
    ['window selector', 'select', 'Chip 1h / 6h / 24h(default) / 7d'],
    ['response time chart', 'chart', 'area p50/p95 over time, ms'],
    ['time to first token chart', 'chart', 'area p50/p95 TTFT over time, ms'],
    ['latency by model chart', 'chart', 'horizontal bar top-10 by avg latency'],
    ['warn banner', 'badge', 'warn on load fail — values may be partial'],
    ['[Prometheus variant] SLOs strip (5)', 'kpi', 'TTFT p95 · TPOT p95 · req/sec · cache hit % · error %'],
    ['[Prometheus variant] latency over time (3 charts)', 'chart', 'TTFT p95 / TPOT p95 / Request duration p95 by model'],
    ['[Prometheus variant] throughput (2 charts)', 'chart', 'Request rate by model · Token rate by direction'],
    ['[Prometheus variant] reliability+quality (2 charts)', 'chart', 'finish_reason distribution · errors by class'],
    ['[Prometheus variant] operations strip (5)', 'kpi', 'chat turns/s · tool calls/s · agents/s · tool err % · agent err %'],
    ['[Prometheus variant] operations charts', 'chart', 'chat turns by model · top tools · dispatch rate · sub-agent invocations · tokens/turn · cache-read'],
    ['time range (Prom variant)', 'select', 'TimeWindow 1h/6h/12h/24h/7d/30d/90d'],
    ['routing note', 'badge', 'llm-performance → PerformancePane; gen_ai.* LLMPerformancePane is a Dashboard subtab variant'],
  ]),

  /* ---- Flows ---- */
  workflows: inv('Flows', [
    ['Flows page title + status meta', 'kpi', "PageHead 'Flows' + StatusDot + '<N> workflows · <N> active · <N> executions (24h) · <pct> success'"],
    ['refresh', 'action-button', 'ghost; refetches workflows + stats + kpis'],
    ['+ new workflow', 'action-button', 'primary; opens WorkflowModal in create mode'],
    ['Subtabs', 'tab', 'workflows | executions | costs | failures | audit'],
    ['KPI strip (5)', 'kpi', 'workflows · active (+public) · executions(24h) · success rate(tone) · total cost(24h, avg/run)'],
    ['high-failure warn banner', 'badge', 'warn when top_failing_nodes>0: "N node failures in 24h across M nodes"'],
    ['action flash banner', 'badge', 'info/ok/warn/err Banner for mutation notices (4s auto-dismiss)'],
    ['delete confirm inline', 'badge', 'ConfirmInline err, "delete workflow", soft-delete (runs preserved)'],
    ['workflows search', 'text-input', 'FilterRow "search workflows · names, descriptions, owners…"'],
    ['status filter chips', 'select', 'all | active | disabled (client-side); right "X / Y match"'],
    ['workflows table', 'table', 'Workflow(Toggle+name+desc) | Visibility | Owner | Status | Nodes | Runs | Success | Updated | actions'],
    ['enable/disable toggle (per row)', 'toggle', 'PUT /api/workflows/:id {is_active}'],
    ['edit (per row)', 'action-button', 'opens WorkflowModal edit mode'],
    ['del (per row)', 'action-button', 'delete ConfirmInline → DELETE /admin/workflows/:id'],
    ['empty state CTA', 'action-button', 'EmptyState "No workflows yet" + "+ new workflow"'],
    ['WorkflowModal (create/edit form)', 'form', 'name(req unique) | description | visibility(private/team/public). create POST, edit PUT + PATCH visibility'],
    ['detail side-panel (4 tabs)', 'side-panel', 'header name + "N runs · M nodes · owner"; overview | runs | cost | audit'],
    ['detail · overview', 'list', 'id, name, description, owner, visibility, status, nodes, runs, successful, failed, success rate, created, updated + open in canvas + edit'],
    ['detail · runs', 'table', 'useAdminWorkflowRuns(id,50); Started | Status | Nodes | Duration | Cost'],
    ['detail · cost', 'kpi', 'last-50-runs roll-up: total | cost-bearing | avg/run'],
    ['detail · audit', 'list', 'Feed of flow audit-log entries filtered to this workflow'],
  ]),
  executions: inv('Executions', [
    ['Executions subtab (of Flows)', 'tab', 'WorkflowsPage initialTab=executions; global list, paged 50'],
    ['executions search', 'text-input', 'FilterRow "search executions · workflow · user · id…"'],
    ['exec status filter chips', 'select', 'all | completed | completed_with_errors | running | failed | pending (server-side)'],
    ['executions table', 'table', 'Workflow(name+triggerType+id8) | User | Status | Nodes | Duration | Cost | Started'],
  ]),
  'flow-costs': inv('Costs', [
    ['Costs subtab (of Flows)', 'tab', 'WorkflowsPage initialTab=costs → CostsPane'],
    ['top expensive flows', 'kpi', 'SectionBar + KpiGrid(5) from kpis.top_expensive_flows: flowName / $totalCost / flowId8'],
    ['cost rollup period chips', 'select', '7d | 30d | 90d → useFlowCost(period,workflow)'],
    ['cost summary KPIs (4)', 'kpi', 'total cost | executions(cost-bearing) | tokens | avg/run'],
    ['cost-by-workflow table', 'table', 'Workflow(label + N models) | Executions | Tokens | Cost | Avg/Run'],
  ]),
  failures: inv('Flows', [
    ['Failures subtab (of Flows)', 'tab', 'WorkflowsPage tab=failures → FailuresPane'],
    ['top failing nodes', 'table', '/admin/flows/failing-nodes; Node(nodeId+type) | Failures | % of failures | Flows affected | Last seen'],
  ]),
  'audit-logs': inv('Flows', [
    ['Audit subtab (of Flows page)', 'tab', 'WorkflowsPage tab=audit → AuditPane: Feed of FlowAuditLogEntry (last 50)'],
    ['Audit Logs page (standalone leaf)', 'kpi', 'AuditLogsPage — "<N> events loaded · SSE/poll status · <N> errors (24h)"'],
    ['pause / resume', 'action-button', 'ghost; toggles SSE live feed + 5s REST poll'],
    ['refresh', 'action-button', 'ghost; manual logsQ.refetch'],
    ['export csv', 'action-button', 'primary; GET /admin/audit-logs/export?format=csv → audit-logs-<date>.csv'],
    ['audit sub-tabs (8)', 'tab', 'all | admin | errors | auth | sessions | resource | audit chain | file custody'],
    ['KPI strip (4)', 'kpi', 'events(24h) | errors(24h) | auth events | admin actions(24h)'],
    ['audit search', 'text-input', 'FilterRow "search user / action / resource / query…"'],
    ['scope chips', 'select', 'all | admin | user → re-keys logType'],
    ['resource chips', 'select', 'all + LLMProvider | MCPServer | Workflow | User | Token | Prompt | capability'],
    ['status chips', 'select', 'all | success | error'],
    ['range chips', 'select', '1h | 6h | 24h | 7d | 30d'],
    ['live feed (all/admin/auth/resource)', 'list', 'Feed(max 200): ts/dot/actor/[type] action on resource·id12/error80/ok|fail. SSE + 5s poll'],
    ['errors pane', 'list', 'failed user queries Feed (ts/actor/queryType/errorMessage120/errorCode)'],
    ['sessions pane', 'list', 'chat sessions Feed (ts/actor/title/messageCount/model/id8)'],
    ['audit chain pane (AU-6/AU-10)', 'list', 'integrity verdict band (INTACT/BROKEN at index) + Feed (ts/SESSION_START|TOOL_CALL/userId/action/hash10)'],
    ['file custody pane (AU-10/AU-6)', 'list', 'file chain-of-custody Feed (ts/actor/action/fileName+size/from IP/denied reason/outcome)'],
    ['event detail side-panel', 'side-panel', 'EventDetail: summary grid + query pre + raw record JSON (secrets masked)'],
  ]),
  credentials: inv('Credentials', [
    ['Flow Operations hub host', 'tab', 'FlowsExtrasHubPage; credentials | governance | kpi dashboard | teams'],
    ['hub KPI strip (4)', 'kpi', 'credentials stored | governance violations | kpi snapshots | teams'],
    ['read-only banner', 'badge', 'info: mutations route through v2 fallback (?v3=0)'],
    ['credentials scope filter chips', 'select', 'all | global | workflow | group'],
    ['credentials search', 'text-input', 'FilterRow "search secrets…" (name + description)'],
    ['workflow secrets table', 'table', 'NAME | SCOPE | ALLOWED NODES | ACCESSES | LAST ROTATED | UPDATED. Read-only; "use {{secret:name}}"'],
    ['wire fields (data surface)', 'list', 'id, name, description, scope, workflow_id, group_id, allowed_node_types[], access_count, last_accessed_at, last_rotated_at, created_by, updated_by, created_at, updated_at'],
  ]),
  governance: inv('Governance', [
    ['Governance tab (of Flow Operations hub)', 'tab', 'GovernancePane; /admin/workflow-settings live config, READ-ONLY (LockedTag every row)'],
    ['read-only banner', 'badge', 'info: governance config renders live; mutations stay in v2'],
    ['execution limits section', 'form', 'defaultNodeTimeout | maxNodeTimeout | maxExecutionTime | maxNodesPerWorkflow | maxConcurrentExecutions | maxConcurrentPerUser | maxExecutionsPerHourPerUser'],
    ['cost governance section', 'form', 'defaultPerExecutionBudget | maxPerExecutionBudget | defaultDailyBudgetPerUser | defaultMonthlyBudgetPerUser | onBudgetExceeded'],
    ['model & agent section', 'form', 'maxAgentTurns | maxToolCallsPerAgent | agentCostBudgetCap | requireApprovalForHighRiskTools | highRiskToolsList'],
    ['node & error handling section', 'form', 'disabledNodeTypes | defaultRetryCount | defaultRetryDelay | defaultBackoffStrategy | defaultOnError'],
    ['memory & context section', 'form', 'crossModeMemoryEnabled | memoryRetentionDays | maxMemoryEntriesPerUser'],
    ['governance-violations KPI proxy', 'kpi', 'disabledNodeTypes length (proxy, not real runtime violations)'],
  ]),
  'kpi-dashboard': inv('KPIs', [
    ['KPI Dashboard tab (of Flow Operations hub)', 'tab', 'KpiDashboardPane; /admin/flows/kpis?window'],
    ['window chips', 'select', '1h | 6h | 24h | 7d | 30d | 90d'],
    ['headline KPIs (4)', 'kpi', 'executions | success rate(tone) | p95 latency | avg cost/run (+total)'],
    ['secondary KPIs (3)', 'kpi', 'latency p50 | latency p99 | failing node count(tone warn)'],
    ['top failing nodes bar list', 'chart', 'BarList top 10 by failureCount'],
    ['top expensive flows bar list', 'chart', 'BarList top 10 by totalCostUsd'],
  ]),
  teams: inv('Teams', [
    ['Teams tab (of Flow Operations hub)', 'tab', 'TeamsPane; /admin/teams, READ-ONLY'],
    ['teams active filter chips', 'select', 'all | active | inactive'],
    ['teams search', 'text-input', 'FilterRow "search teams…"'],
    ['teams table', 'table', 'NAME(display+name) | STATUS | MEMBERS | SHARED FLOWS | COST CENTER | BILLING CONTACT | UPDATED'],
    ['wire fields (data surface)', 'list', 'id, name, display_name, description, parent_group_id, cost_center, billing_contact_email, metadata, is_active, created_by, created_at, updated_at, member_count, shared_flows_count'],
  ]),

  /* ---- Agents ---- */
  'agent-registry': inv('Agents', [
    ['Agents hub host + meta', 'kpi', 'AgentsHubPage; "<N> registered · <N> executions (24h) · $<X> spent"'],
    ['+ register agent', 'action-button', 'primary; opens AgentModal create mode'],
    ['Subtabs', 'tab', 'registry | ops | skills | executions'],
    ['hub KPI strip (5)', 'kpi', 'agents | active(24h)+succ% | executions(24h) | tokens(24h) | cost(24h)'],
    ['action flash banner + delete confirm', 'badge', 'info/ok/warn/err Banner; ConfirmInline "disable agent" soft-delete'],
    ['registry kind filter chips', 'select', 'all | platform | background | enabled | disabled'],
    ['registry search', 'text-input', 'FilterRow "search agents · names, types, descriptions…"'],
    ['agent registry table', 'table', 'Agent(Toggle+name+desc) | Type | Kind | Model | Skills | Tools | Status | Created | actions'],
    ['enable/disable toggle (per row)', 'toggle', 'PUT /admin/agents/:id {enabled}'],
    ['edit / del (per row)', 'action-button', 'edit→AgentModal; del→ConfirmInline → DELETE (soft)'],
    ['empty state CTA', 'action-button', 'EmptyState "No agents registered" + "+ new agent"'],
    ['AgentModal (register/edit form)', 'form', 'display name(req) | name slug(auto) | agent type | description | skills(Chip multi) | enabled(Toggle)'],
    ['agent detail side-panel (5 tabs)', 'side-panel', 'header + "agent_type · N skills · M tools"; overview | skills | runs | cost | audit'],
    ['detail · overview', 'list', 'StatusDot + kind chip + description; identity Dl + fleet 24h MiniGrid + actions'],
    ['detail · skills', 'table', 'Skill(name+desc) | Type | Source'],
    ['detail · runs', 'table', 'When | Status | Model | Dur | Tok'],
    ['detail · cost', 'kpi', 'fleet 24h MiniGrid: total | runs | avg/run'],
    ['detail · audit (AU-6)', 'list', 'useAgentAuditChain: tamper-evident hash-chain Feed (ts/action/userId/action→target/hash12)'],
    ['AgentTestModal', 'form', 'task textarea + run test → POST /admin/agents/:id/test; response pre + metrics (model/elapsed/tools)'],
  ]),
  'agent-ops': inv('Agents', [
    ['Ops tab (of Agents hub)', 'tab', 'OpsPane; real-time running agents. stats 15s / live 5s / fleet 15s'],
    ['partial-failure banner', 'badge', 'warn when any of stats/live/fleet unreachable'],
    ['ops KPIs (4)', 'kpi', 'active now | runs today(+failed) | runs(7d)+avg latency | success rate(7d)+$spent'],
    ['executions over time chart', 'chart', 'MetricChart area, timeSeries.agentExecutions (24h)'],
    ['in-flight live feed', 'list', '/admin/agents/executions/live (5s, top 12): ts/status/agent role/status·orchestration/$cost'],
    ['fleet health table', 'table', 'Agent | Runs 24h | Success(pct) | p50 | Cost 24h. Row→detail'],
  ]),
  'agent-skills': inv('Agents', [
    ['Skills tab (of Agents hub)', 'tab', 'SkillsPane; /admin/agents/skills'],
    ['skill type filter chips', 'select', 'all | prompt_module | tool_bundle | workflow | code_template + extras'],
    ['skills search', 'text-input', 'FilterRow "search skills · names, descriptions, tags…"'],
    ['agent skills table', 'table', 'Skill(display+desc) | Type | Source | Tags(3+N) | Used by | Created'],
    ['wire fields (data surface)', 'list', 'id, name, display_name, description, type, source, tags[], usage_count, enabled, created_at'],
  ]),
  'agent-executions': inv('Executions', [
    ['Executions tab (of Agents hub)', 'tab', 'agents ExecutionsPane; /admin/agents/executions (agentRunLog), limit 50'],
    ['exec status filter chips', 'select', 'all | completed | running | failed | pending | cancelled'],
    ['executions search', 'text-input', 'FilterRow "search executions · agent · model · user · id…"'],
    ['agent executions table', 'table', 'Agent(name/type+id8) | User(id12) | Status | Model | Duration | Tokens | Cost | Started'],
  ]),

  /* ---- Tools & MCP ---- */
  'mcp-fleet': inv('Tools&MCP', [
    ['PageHead title + meta', 'kpi', "title 'MCP Fleet'; meta '{total} servers · {healthy} healthy · {tools} tools indexed'"],
    ['bulk actions', 'action-button', 'ghost btn (bulk-actions affordance)'],
    ['+ add server', 'action-button', 'primary → opens MCPServerModal in create mode'],
    ['total servers KPI', 'kpi', 'value=summary.total; sub "{healthy} healthy · {attention} attention"'],
    ['health KPI', 'kpi', 'tri-count healthy/degraded/down'],
    ['tools indexed KPI', 'kpi', 'sum of tools across servers'],
    ['Subtabs', 'tab', 'overview · health · tools · activity'],
    ['servers search', 'text-input', 'FilterRow "server, transport, host…"'],
    ['status filter chips', 'select', 'all / healthy / degraded / down (live counts)'],
    ['servers table', 'table', 'Server(name+transport) | Status | Tools | Calls(24h) | p50 | Err% | Host | Uptime | Enabled(Toggle) | actions'],
    ['Health pane', 'table', 'Server | Status(StatusDot) | Last Probe | Last Error | Transport'],
    ['Tools pane', 'table', 'flattens all server tools; Tool | Server | Calls(24h) | p50 | Err%'],
    ['Activity pane', 'table', 'scoped audit resourceType=MCPServer; When | Actor | Action | Resource | Result'],
    ['Detail SidePanel', 'side-panel', 'overview · tools · logs; headActions re-probe + edit'],
    ['MCPServerModal', 'form', 'name(req) | transport(stdio/streamable-http/sse) | command/url | env(JSON) | enabled(Toggle)'],
    ['Mutations', 'action-button', 'create POST; edit PUT /:id; delete DELETE; re-probe POST /:id/test'],
  ]),
  'enriched-tools': inv('Tools&MCP', [
    ['PageHead title + meta', 'kpi', '"Enriched Tools" — semantic descriptions + few-shot examples layered over raw MCP tools'],
    ['refresh', 'action-button', 'ghost; refetch enrichment registry'],
    ['+ add enrichment', 'action-button', 'primary; opens EnrichmentModal'],
    ['KPI: enriched', 'kpi', 'count tools with curated description/examples'],
    ['KPI: coverage', 'kpi', '{enriched}/{totalTools} of fleet'],
    ['search', 'text-input', 'FilterRow "tool, server, tag…"'],
    ['server filter chips', 'select', 'all + per-server'],
    ['enriched tools table', 'table', 'Tool | Server | Description override | Examples(#) | Embedded(yes/no) | Updated'],
    ['EnrichmentModal', 'form', 'tool(locked) | description(textarea) | few-shot examples(JSON) | tags | re-embed(toggle)'],
    ['Mutations', 'action-button', 'create/edit PUT; delete DELETE; re-embed POST'],
  ]),
  'skills-ecosystem': inv('Tools&MCP', [
    ['PageHead title + meta', 'kpi', '"Skills Ecosystem" — multi-source skill registry (own + upstream Apache-2.0)'],
    ['+ add source', 'action-button', 'primary; opens SourceModal (git url + license check)'],
    ['Subtabs', 'tab', 'installed · sources · marketplace'],
    ['KPI: installed skills', 'kpi', 'count enabled skills'],
    ['KPI: sources', 'kpi', 'openagentic-skills + anthropics/skills + openclaw …'],
    ['sources table', 'table', 'Source | License | Skills | Last Sync | Trust | Enabled(Toggle)'],
    ['skills table', 'table', 'Skill | Source | Type | Used by | License | Enabled(Toggle) | view_skill'],
    ['SourceModal', 'form', 'git url(req) | branch | license(detected) | codeowner gate(toggle) | sync schedule'],
    ['Mutations', 'action-button', 'add source POST; sync POST; toggle PUT; remove DELETE'],
  ]),

  /* ---- Integrations ---- */
  slack: inv('Integrations', [
    ['PageHead title + meta', 'kpi', '"Slack" — workspace connection + channel routing'],
    ['connection card', 'form', 'workspace | bot | status(StatusDot) | reconnect'],
    ['channels table', 'table', 'Channel | Linked users | Inbound(events/slash) | Outbound | Last event'],
    ['account links table', 'table', 'Slack user | platform user | linked at'],
    ['settings section', 'form', 'eventUrl | slashCommandUrl | signingSecret(masked) | botToken(masked) | enabled(toggle)'],
    ['Mutations', 'action-button', 'connect OAuth; rotate token (HITL); disable'],
  ]),
  'ms-teams': inv('Integrations', [
    ['PageHead title + meta', 'kpi', '"Microsoft Teams" — tenant connection'],
    ['connection card', 'form', 'tenant | app registration | status | reconnect'],
    ['channels table', 'table', 'Team/Channel | Linked | Last event'],
    ['settings section', 'form', 'appId | clientSecret(masked) | webhookUrl | enabled(toggle)'],
    ['Mutations', 'action-button', 'connect; rotate; disable'],
  ]),
  'integration-logs': inv('Integrations', [
    ['PageHead title + meta', 'kpi', '"Integration Logs" — inbound/outbound event trail'],
    ['integration filter chips', 'select', 'all | slack | teams | github'],
    ['direction chips', 'select', 'all | inbound | outbound'],
    ['logs table', 'table', 'When | Integration | Direction | Event | Status | Payload(id)'],
    ['event detail side-panel', 'side-panel', 'raw payload JSON (masked)'],
  ]),

  /* ---- Prompts ---- */
  'prompt-modules': inv('Prompts', [
    ['PageHead title + meta', 'kpi', '"Modules" — DB-backed, versioned, per-tenant prompt modules'],
    ['+ new module', 'action-button', 'primary; PromptModal'],
    ['tier filter chips', 'select', 'all | system | behavioral | tool'],
    ['search', 'text-input', 'FilterRow "module, tag…"'],
    ['modules table', 'table', 'Module | Tier | Tenant scope | Version | Updated | Enabled(Toggle) | actions'],
    ['module detail side-panel', 'side-panel', 'overview · versions · diff; edit (HITL on system tier)'],
    ['PromptModal', 'form', 'name(req) | tier(select) | tenant scope(select) | content(textarea) | enabled(toggle)'],
    ['Mutations', 'action-button', 'create/edit PUT (versioned); rollback; toggle'],
  ]),
  'pipeline-settings': inv('Prompts', [
    ['PageHead title + meta', 'kpi', '"Pipeline Settings" — prompt assembly order + layers'],
    ['layers section', 'form', 'systemPromptLayer(order) | behavioralLayer(order) | toolLayer(order) | groundingLayer(toggle)'],
    ['behavior section', 'form', 'clarifyFirst(toggle) | artifactForce(select off/judge/on) | groundingDefault(toggle)'],
    ['save', 'action-button', 'primary; PUT (HITL)'],
  ]),
  'prompt-effectiveness': inv('Prompts', [
    ['PageHead title + meta', 'kpi', '"Effectiveness" — per-module A/B + win-rate'],
    ['window selector', 'select', '7d / 30d / 90d'],
    ['KPI strip (3)', 'kpi', 'modules tracked | avg win-rate | regressions'],
    ['effectiveness table', 'table', 'Module | Version | Win-rate | Sample | Trend'],
    ['win-rate chart', 'chart', 'line'],
  ]),
  'prompt-metrics': inv('Prompts', [
    ['PageHead title + meta', 'kpi', '"Metrics" — prompt token + latency overhead'],
    ['window selector', 'select', '1h / 24h / 7d'],
    ['KPI strip (4)', 'kpi', 'avg prompt tokens | assembly latency | cache hit % | layers active'],
    ['tokens over time chart', 'chart', 'area'],
  ]),

  /* ---- Content ---- */
  templates: inv('Content', [
    ['PageHead title + meta', 'kpi', '"Templates" — flow + artifact + message templates'],
    ['+ new template', 'action-button', 'primary; TemplateModal'],
    ['type filter chips', 'select', 'all | flow | artifact | message'],
    ['templates table', 'table', 'Template | Type | Owner | Used by | Updated | Enabled(Toggle)'],
    ['TemplateModal', 'form', 'name | type(select) | body(textarea) | visibility | enabled(toggle)'],
    ['Mutations', 'action-button', 'create/edit/delete'],
  ]),
  'shared-kb': inv('Content', [
    ['PageHead title + meta', 'kpi', '"Shared Knowledge Base" — RAG corpora (Milvus)'],
    ['+ new KB', 'action-button', 'primary; KBModal'],
    ['kb table', 'table', 'KB | Vectors | Embedding model | Docs | Last reindex | Status'],
    ['kb detail side-panel', 'side-panel', 'docs · reindex · access; reindex action'],
    ['Mutations', 'action-button', 'create; reindex POST; delete'],
  ]),
  'data-layer': inv('Content', [
    ['PageHead title + meta', 'kpi', '"Unified Data Layer" — datastores + connections'],
    ['+ add datastore', 'action-button', 'primary; DatastoreModal'],
    ['datastores table', 'table', 'Datastore | Type(pg/redis/s3/milvus) | Status | Used by | Connection(masked)'],
    ['DatastoreModal', 'form', 'name | type(select) | dsn(masked) | scope | enabled(toggle)'],
    ['Mutations', 'action-button', 'create/edit/delete; test connection'],
  ]),
  'user-memory': inv('Content', [
    ['PageHead title + meta', 'kpi', '"User Memory" — cross-mode memory entries'],
    ['settings section', 'form', 'crossModeMemoryEnabled(toggle) | retentionDays(number) | maxEntriesPerUser(number)'],
    ['user filter', 'select', 'per-user select'],
    ['memory table', 'table', 'User | Entries | Last updated | Size'],
    ['Mutations', 'action-button', 'purge user memory (HITL)'],
  ]),

  /* ---- Observability ---- */
  'cluster-health': inv('Observability', [
    ['PageHead title + meta', 'kpi', '"Cluster Health" — node + pod health (k3s)'],
    ['refresh', 'action-button', 'ghost; live 15s'],
    ['KPI strip (4)', 'kpi', 'nodes ready | pods running | GPU util | cordoned'],
    ['nodes table', 'table', 'Node | Role | CPU% | Mem% | GPU% | Pods | Status | Kubelet'],
    ['resource charts', 'chart', 'CPU/Mem over time'],
  ]),
  analytics: inv('Observability', [
    ['PageHead title + meta', 'kpi', '"Usage Analytics" — tokens, requests, active users'],
    ['window selector', 'select', '24h / 7d / 30d / 90d'],
    ['KPI strip (4)', 'kpi', 'token burn | requests | active users | sessions'],
    ['usage over time chart', 'chart', 'area by model'],
    ['top users table', 'table', 'User | Tokens | Requests | Cost'],
  ]),
  'user-activity': inv('Observability', [
    ['PageHead title + meta', 'kpi', '"User Activity" — per-user session + tool activity'],
    ['user filter', 'select', 'per-user'],
    ['window selector', 'select', '24h / 7d / 30d'],
    ['activity table', 'table', 'User | Last seen | Sessions | Tokens(30d) | MFA'],
    ['activity timeline chart', 'chart', 'line'],
  ]),
  errors: inv('Observability', [
    ['PageHead title + meta', 'kpi', '"Monitoring & Errors" — error stream + classes'],
    ['refresh', 'action-button', 'ghost; live'],
    ['class filter chips', 'select', 'all | 4xx | 5xx | timeout | dlp-block'],
    ['errors table', 'table', 'When | Class | Service | Message | Count | Last seen'],
    ['error detail side-panel', 'side-panel', 'stack/context (masked)'],
  ]),
  slo: inv('Observability', [
    ['PageHead title + meta', 'kpi', '"SLOs" — latency + availability objectives'],
    ['SLO strip (5)', 'kpi', 'TTFT p95 | TPOT p95 | availability | error budget | burn rate'],
    ['SLO table', 'table', 'SLO | Target | Current | Budget remaining | Status'],
    ['burn-rate chart', 'chart', 'line'],
  ]),
  'context-window': inv('Observability', [
    ['PageHead title + meta', 'kpi', '"Context Window" — per-session context utilization + compaction'],
    ['window selector', 'select', '1h / 24h / 7d'],
    ['KPI strip (4)', 'kpi', 'avg context tokens | max window used | compaction events | overflow rejects'],
    ['utilization over time chart', 'chart', 'area'],
    ['sessions table', 'table', 'Session | Model | Context used | Window | Compactions'],
  ]),
  embeddings: inv('Observability', [
    ['PageHead title + meta', 'kpi', '"Embeddings" — embedding throughput + Milvus'],
    ['KPI strip (4)', 'kpi', 'vectors | embed req/s | avg latency | model'],
    ['collections table', 'table', 'Collection | Vectors | Dim | Index | Last reindex'],
    ['throughput chart', 'chart', 'area'],
  ]),
  audit: inv('Observability', [
    ['PageHead title + meta', 'kpi', '"Audit Logs" — full platform audit (same engine as Flows audit)'],
    ['audit sub-tabs (8)', 'tab', 'all | admin | errors | auth | sessions | resource | audit chain | file custody'],
    ['KPI strip (4)', 'kpi', 'events(24h) | errors(24h) | auth events | admin actions(24h)'],
    ['audit search', 'text-input', 'FilterRow "user / action / resource / query…"'],
    ['scope chips', 'select', 'all | admin | user'],
    ['resource chips', 'select', 'all + LLMProvider | MCPServer | Workflow | User | Token | Prompt | capability'],
    ['range chips', 'select', '1h | 6h | 24h | 7d | 30d'],
    ['live feed', 'list', 'Feed(200): ts/dot/actor/[type] action on resource·id12/result. SSE + 5s poll'],
    ['export csv', 'action-button', 'primary; GET export?format=csv'],
    ['event detail side-panel', 'side-panel', 'summary grid + raw JSON (masked)'],
  ]),
  feedback: inv('Observability', [
    ['PageHead title + meta', 'kpi', '"Feedback" — thumbs + free-text on responses'],
    ['sentiment filter chips', 'select', 'all | up | down'],
    ['feedback table', 'table', 'When | User | Session | Sentiment | Comment | Model'],
    ['feedback detail side-panel', 'side-panel', 'full transcript context + sentiment'],
  ]),
  'test-harness': inv('Observability', [
    ['PageHead title + meta', 'kpi', '"Test Harness" — real-model scenario runs (Q*.yaml)'],
    ['+ run scenario', 'action-button', 'primary; pick scenario → hal gpt-oss:20b'],
    ['scenarios table', 'table', 'Scenario | Last run | Status(red/green) | Duration | Evidence'],
    ['run detail side-panel', 'side-panel', 'NDJSON wire + DOM walk + pass/fail line'],
    ['Mutations', 'action-button', 'run POST; block build on RED'],
  ]),
  chargeback: inv('Costs', [
    ['PageHead title + meta', 'kpi', '"Cost Management" — chargeback by team/tenant/model'],
    ['window selector', 'select', '7d / 30d / 90d'],
    ['KPI strip (4)', 'kpi', 'total spend | projected MTD | top cost center | over-budget teams'],
    ['cost by dimension chips', 'select', 'team | tenant | model | provider'],
    ['cost table', 'table', 'Dimension | Spend | Tokens | % of total | Budget | Status'],
    ['spend over time chart', 'chart', 'stacked area'],
  ]),

  /* ---- System & Security ---- */
  users: inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"User Management" — accounts, roles, MFA'],
    ['+ invite user', 'action-button', 'primary; UserModal'],
    ['status filter chips', 'select', 'all | active | locked | service'],
    ['users search', 'text-input', 'FilterRow "name, email, role…"'],
    ['users table', 'table', 'User(name+email) | Role | Status | Tenant | MFA | Tokens(30d) | Last seen | actions'],
    ['user detail side-panel', 'side-panel', 'overview · sessions · permissions · audit; lock/unlock, reset MFA (HITL)'],
    ['UserModal', 'form', 'email(req) | name | role(select) | tenant(select) | requireMfa(toggle) | enabled(toggle)'],
    ['Mutations', 'action-button', 'invite POST; edit PUT; lock/unlock; delete (HITL)'],
  ]),
  'auth-access': inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"Auth Access Control" — local user access policy'],
    ['policy section', 'form', 'requireMfaAllUsers(toggle) | sessionLifetime(number) | allowedDomains(csv)'],
    ['save', 'action-button', 'primary; PUT (HITL)'],
  ]),
  permissions: inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"User Permissions" — capability allow/ask/deny matrix (AU-3)'],
    ['user/role filter', 'select', 'per-user or per-role'],
    ['permission matrix', 'table', 'Capability rows × allow/ask/deny columns (toggle per cell)'],
    ['Mutations', 'action-button', 'set permission PUT (HITL); audit trail to capability resource'],
  ]),
  'user-lockouts': inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"User Lockouts" — locked accounts + auth-failure trail'],
    ['status filter chips', 'select', 'all | locked | auto-locked | manual'],
    ['lockouts table', 'table', 'User | Reason | Failed attempts | Locked at | Source IP | actions(unlock)'],
    ['Mutations', 'action-button', 'unlock POST (HITL); audit to User resource'],
  ]),
  tokens: inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"API Tokens" — PATs + service tokens'],
    ['+ create token', 'action-button', 'primary; TokenModal (shows secret once)'],
    ['status filter chips', 'select', 'all | active | revoked'],
    ['tokens table', 'table', 'Token(name+prefix) | Owner | Scopes | Created | Last used | Status | actions'],
    ['TokenModal', 'form', 'name | owner | scopes(multi) | expiry(select)'],
    ['Mutations', 'action-button', 'create POST (secret once); revoke DELETE'],
  ]),
  'system-settings': inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"System Settings" — platform-wide toggles'],
    ['platform section', 'form', 'platformName | defaultTheme(select) | accentColor | maintenanceMode(toggle)'],
    ['feature flags section', 'form', 'groundingDefault(toggle) | artifactIntentJudge(toggle)'],
    ['save', 'action-button', 'primary; PUT (HITL)'],
  ]),
  'rate-limits': inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"Rate Limits" — per-tier request + token caps'],
    ['+ add tier', 'action-button', 'primary; TierModal'],
    ['tiers table', 'table', 'Tier | Req/min | Tokens/day | Burst | Applies to | Enabled(Toggle)'],
    ['TierModal', 'form', 'name | reqPerMin(number) | tokensPerDay(number) | burst(number) | appliesTo(select)'],
    ['Mutations', 'action-button', 'create/edit/delete (HITL)'],
  ]),
  'network-security': inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"Network Security" — egress netpol + IP allowlists'],
    ['policy section', 'form', 'defaultEgress(select none/allowlist/full) | ipAllowlist(csv) | mtlsRequired(toggle) | privateLinkOnly(toggle)'],
    ['netpol table', 'table', 'Service | Egress | Allowed CIDRs | Status'],
    ['save', 'action-button', 'primary; PUT (HITL)'],
  ]),
  'webhook-security': inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"Webhook Security" — inbound webhook signing + allowlist'],
    ['+ add webhook', 'action-button', 'primary; WebhookModal'],
    ['webhooks table', 'table', 'Webhook | Source | Signing | Last delivery | Status | Enabled(Toggle)'],
    ['WebhookModal', 'form', 'name | url | signingSecret(masked) | allowedSources(csv) | enabled(toggle)'],
    ['Mutations', 'action-button', 'create/edit/delete; rotate secret (HITL)'],
  ]),
  'dlp-config': inv('System&Security', [
    ['PageHead title + meta', 'kpi', '"DLP Configuration" — data-loss-prevention rules + blocks'],
    ['policy section', 'form', 'dlpEnabled(toggle) | mode(select block/redact/audit) | patterns(JSON regex set) | piiDetection(toggle)'],
    ['recent blocks table', 'table', 'When | Session | Pattern | Action | Actor'],
    ['save', 'action-button', 'primary; PUT (HITL)'],
  ]),
}

/** Total options across all leaves — for the console boot log. */
export const ADMIN_INV_OPTION_COUNT = Object.values(ADMIN_INV).reduce(
  (a, i) => a + i.opts.length,
  0,
)
