/**
 * Server-Side Rendering Service
 *
 * Handles DOCX / Markdown / Text export via /api/render/export. PDF export
 * runs client-side (ClientExportService in the UI — html2canvas + jsPDF),
 * so puppeteer + chromium are not needed here.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle
} from 'docx';
import { Logger } from 'pino';
import * as XLSX from 'xlsx';

// Sprint B (2026-05-18) — XLSX per-artifact export. The input artifact is
// EITHER a streaming_table (columns[] + rows[]) OR a compose_visual data
// payload (data.{rows|nodes|series|links} — the first array is used).
// Output is a single-sheet workbook the route hands back as binary.
export interface ExportArtifactInput {
  /** Discriminant — streaming_table | compose_visual | <anything else throws>. */
  type: string;
  /** streaming_table: explicit header row. */
  columns?: string[];
  /** streaming_table: row data, either object-shaped or positional. */
  rows?: Array<Record<string, unknown> | unknown[]>;
  /** compose_visual / artifact_render: structured chart-data payload. */
  data?: Record<string, unknown>;
  /** Optional display title — currently informational; sheet name is "Artifact". */
  title?: string;
  // Pass-through fields we don't care about for export.
  [k: string]: unknown;
}

export interface ExportArtifactOptions {
  /** Optional sheet name override. Defaults to "Artifact". */
  sheetName?: string;
  /** Optional display title — written to workbook custom properties. */
  title?: string;
}

interface ExportMessage {
  id: string;
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  timestamp: string;
  metadata?: any;
  toolCalls?: any[];
  mcpCalls?: any[];
}

interface ExportOptions {
  format: 'docx' | 'markdown' | 'text';
  includeTimestamps?: boolean;
  includeMetadata?: boolean;
  title?: string;
  author?: string;
  theme?: 'light' | 'dark';
}

export class RenderingService {
  private logger: Logger;

  constructor(logger: Logger) {
    this.logger = logger;
  }

  async initialize() {
    // no-op — kept for API compatibility with routes/render.ts
  }

  async destroy() {
    // no-op
  }

  async exportToDOCX(messages: ExportMessage[], options: ExportOptions): Promise<Buffer> {
    try {
      const {
        title = 'Conversation Export',
        author = 'OpenAgenticChat',
        includeTimestamps = true,
        includeMetadata = false
      } = options;

      const documentChildren: any[] = [];

      documentChildren.push(
        new Paragraph({
          text: title,
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 }
        })
      );

      documentChildren.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `Generated by ${author}`,
              italics: true,
              size: 20
            })
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 }
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: new Date().toLocaleString(),
              italics: true,
              size: 20
            })
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 }
        })
      );

      for (const message of messages) {
        const roleLabel = message.role.charAt(0).toUpperCase() + message.role.slice(1);

        const headerRuns: TextRun[] = [
          new TextRun({
            text: roleLabel,
            bold: true,
            color: message.role === 'user' ? '3B82F6' : '6B7280',
            size: 24
          })
        ];

        if (includeTimestamps) {
          headerRuns.push(
            new TextRun({
              text: ` • ${new Date(message.timestamp).toLocaleString()}`,
              italics: true,
              size: 20,
              color: '9CA3AF'
            })
          );
        }

        documentChildren.push(
          new Paragraph({
            children: headerRuns,
            spacing: { before: 200, after: 100 }
          })
        );

        const contentLines = message.content.split('\n');
        let inCodeBlock = false;
        let codeBlockContent: string[] = [];

        for (const line of contentLines) {
          if (line.trim().startsWith('```')) {
            if (!inCodeBlock) {
              inCodeBlock = true;
              codeBlockContent = [];
            } else {
              inCodeBlock = false;
              documentChildren.push(
                new Paragraph({
                  children: [
                    new TextRun({
                      text: codeBlockContent.join('\n'),
                      font: 'Consolas',
                      size: 20
                    })
                  ],
                  shading: {
                    fill: 'F3F4F6'
                  },
                  spacing: { before: 100, after: 100 }
                })
              );
              codeBlockContent = [];
            }
            continue;
          }

          if (inCodeBlock) {
            codeBlockContent.push(line);
          } else if (line.trim()) {
            const parts = line.split('`');
            const textRuns: TextRun[] = [];

            parts.forEach((part, index) => {
              if (index % 2 === 0) {
                if (part) {
                  textRuns.push(new TextRun({
                    text: part,
                    size: 22
                  }));
                }
              } else {
                textRuns.push(new TextRun({
                  text: part,
                  font: 'Consolas',
                  size: 20,
                  shading: { fill: 'F3F4F6' }
                }));
              }
            });

            documentChildren.push(
              new Paragraph({
                children: textRuns.length > 0 ? textRuns : [new TextRun({ text: line, size: 22 })],
                spacing: { after: 100 }
              })
            );
          } else {
            documentChildren.push(
              new Paragraph({
                text: '',
                spacing: { after: 100 }
              })
            );
          }
        }

        if (includeMetadata && (message.toolCalls?.length || message.mcpCalls?.length)) {
          const allCalls = [...(message.toolCalls || []), ...(message.mcpCalls || [])];

          documentChildren.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Tool Calls:',
                  bold: true,
                  size: 20
                })
              ],
              spacing: { before: 100, after: 50 }
            })
          );

          for (const call of allCalls) {
            const toolName = call.name || call.function?.name || 'unknown';
            documentChildren.push(
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${toolName}`,
                    font: 'Consolas',
                    size: 20
                  })
                ],
                indent: { left: 720 }
              })
            );
          }
        }

        documentChildren.push(
          new Paragraph({
            border: {
              bottom: {
                color: 'E5E7EB',
                space: 1,
                style: BorderStyle.SINGLE,
                size: 6
              }
            },
            spacing: { after: 200 }
          })
        );
      }

      const doc = new Document({
        creator: author,
        title: title,
        description: 'Conversation export from OpenAgenticChat',
        sections: [{
          properties: {},
          children: documentChildren
        }]
      });

      const buffer = await Packer.toBuffer(doc);
      return buffer;

    } catch (error) {
      this.logger.error(`DOCX export failed: ${error instanceof Error ? error.message : String(error)}`);
      throw new Error(`Failed to export to DOCX: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  async exportToText(messages: ExportMessage[], options: ExportOptions): Promise<string> {
    const {
      title = 'Conversation Export',
      author = 'OpenAgenticChat',
      includeTimestamps = true,
      includeMetadata = false
    } = options;

    let text = `${title}\n`;
    text += `Generated by ${author}\n`;
    text += `${new Date().toLocaleString()}\n`;
    text += '='.repeat(80) + '\n\n';

    for (const message of messages) {
      const roleLabel = message.role.toUpperCase();
      const timestamp = includeTimestamps
        ? ` [${new Date(message.timestamp).toLocaleString()}]`
        : '';

      text += `${roleLabel}${timestamp}\n`;
      text += '-'.repeat(80) + '\n';
      text += message.content + '\n';

      if (includeMetadata && (message.toolCalls?.length || message.mcpCalls?.length)) {
        const allCalls = [...(message.toolCalls || []), ...(message.mcpCalls || [])];
        text += '\nTool Calls:\n';
        allCalls.forEach(call => {
          const toolName = call.name || call.function?.name || 'unknown';
          text += `  - ${toolName}\n`;
        });
      }

      text += '\n';
    }

    return text;
  }

  async exportToMarkdown(messages: ExportMessage[], options: ExportOptions): Promise<string> {
    const {
      title = 'Conversation Export',
      author = 'OpenAgenticChat',
      includeTimestamps = true,
      includeMetadata = false
    } = options;

    let markdown = `# ${title}\n\n`;
    markdown += `*Generated by ${author}*\n`;
    markdown += `*${new Date().toLocaleString()}*\n\n`;
    markdown += '---\n\n';

    for (const message of messages) {
      const roleLabel = message.role.charAt(0).toUpperCase() + message.role.slice(1);
      const timestamp = includeTimestamps
        ? ` *${new Date(message.timestamp).toLocaleString()}*`
        : '';

      markdown += `## ${roleLabel}${timestamp}\n\n`;
      markdown += message.content + '\n\n';

      if (includeMetadata && (message.toolCalls?.length || message.mcpCalls?.length)) {
        const allCalls = [...(message.toolCalls || []), ...(message.mcpCalls || [])];
        markdown += '**Tool Calls:**\n\n';
        allCalls.forEach(call => {
          const toolName = call.name || call.function?.name || 'unknown';
          markdown += `- \`${toolName}\`\n`;
        });
        markdown += '\n';
      }

      markdown += '---\n\n';
    }

    return markdown;
  }

  // ─────────────────────────────────────────────────────────────────────
  // Sprint B (2026-05-18) — XLSX per-artifact export
  // ─────────────────────────────────────────────────────────────────────

  /**
   * Convert one chat artifact (streaming_table or compose_visual data) to
   * an XLSX Buffer suitable for `Content-Type: application/vnd.openxmlformats-
   * officedocument.spreadsheetml.sheet` download.
   *
   * Discrimination rules:
   *
   *   - `type === 'streaming_table'`: read `columns[]` (header) + `rows[]`.
   *     Object rows are projected via `columns` (extra keys ignored).
   *     Positional rows are inserted as-is. Empty rows → header-only sheet.
   *
   *   - `type === 'compose_visual'` (or `compose_artifact`, `artifact_render`):
   *     auto-detect the primary tabular array under `data.{rows|nodes|series|links|items}`.
   *     If the first row is object-shaped, derive headers from `Object.keys`.
   *
   *   - Anything else: throw with a descriptive message so the caller can
   *     surface a "Cannot export this artifact" toast.
   */
  async exportArtifactToXLSX(
    artifact: ExportArtifactInput,
    options: ExportArtifactOptions = {},
  ): Promise<Buffer> {
    if (!artifact || typeof artifact !== 'object') {
      throw new Error('exportArtifactToXLSX: artifact is required');
    }

    const sheetName = (options.sheetName ?? 'Artifact').slice(0, 31); // xlsx 31-char limit
    const wb = XLSX.utils.book_new();

    let aoa: unknown[][] | null = null;

    if (artifact.type === 'streaming_table') {
      const columns = Array.isArray(artifact.columns) ? artifact.columns : [];
      if (columns.length === 0) {
        throw new Error('exportArtifactToXLSX: streaming_table requires columns[]');
      }
      const rows = Array.isArray(artifact.rows) ? artifact.rows : [];
      aoa = [columns.slice()];
      for (const row of rows) {
        if (Array.isArray(row)) {
          // Positional — clamp/pad to column count
          const r: unknown[] = [];
          for (let i = 0; i < columns.length; i++) r.push(row[i] ?? null);
          aoa.push(r);
        } else if (row && typeof row === 'object') {
          aoa.push(columns.map((c) => (row as Record<string, unknown>)[c] ?? null));
        }
      }
    } else if (
      artifact.type === 'compose_visual' ||
      artifact.type === 'compose_artifact' ||
      artifact.type === 'artifact_render' ||
      artifact.type === 'viz_render'
    ) {
      const data = (artifact.data ?? {}) as Record<string, unknown>;
      // Auto-detect first array among the canonical chart-data slots.
      const candidates = ['rows', 'nodes', 'series', 'links', 'items', 'records'];
      let arr: unknown[] | null = null;
      for (const key of candidates) {
        const v = data[key];
        if (Array.isArray(v) && v.length > 0) {
          arr = v;
          break;
        }
      }
      if (!arr) {
        // Last-ditch: scan top-level for the FIRST array property
        for (const k of Object.keys(data)) {
          if (Array.isArray((data as any)[k])) {
            arr = (data as any)[k];
            break;
          }
        }
      }
      if (!arr) {
        throw new Error(
          `exportArtifactToXLSX: compose_visual data has no tabular array (looked for ${candidates.join(', ')})`,
        );
      }
      const first = arr[0];
      if (first && typeof first === 'object' && !Array.isArray(first)) {
        const headers = Object.keys(first as Record<string, unknown>);
        aoa = [headers];
        for (const row of arr) {
          aoa.push(headers.map((h) => (row as Record<string, unknown>)[h] ?? null));
        }
      } else if (Array.isArray(first)) {
        const width = (first as unknown[]).length;
        aoa = [Array.from({ length: width }, (_, i) => `col${i + 1}`)];
        for (const row of arr) aoa.push((row as unknown[]).slice());
      } else {
        // Scalar array — single "value" column
        aoa = [['value']];
        for (const v of arr) aoa.push([v]);
      }
    } else {
      throw new Error(
        `exportArtifactToXLSX: unsupported artifact type "${String(artifact.type)}" — cannot export to XLSX`,
      );
    }

    if (!aoa) throw new Error('exportArtifactToXLSX: produced no rows (internal error)');

    const ws = XLSX.utils.aoa_to_sheet(aoa);
    XLSX.utils.book_append_sheet(wb, ws, sheetName);

    if (options.title) {
      (wb as any).Props = { ...(wb as any).Props, Title: options.title };
    }

    const out = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
    return Buffer.isBuffer(out) ? out : Buffer.from(out as ArrayBuffer);
  }
}
