/**
 * Copyright 2026 Gnomus.ai
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * UserProfileService — Living "User DNA" document per user.
 *
 * Extracts signals from feedback, tool usage, conversation patterns, code/flow work.
 * Stored as singleton profile row (user_profiles table). Updated incrementally.
 * style_dna regenerated by LLM during compaction.
 */

import { PrismaClient } from '@prisma/client';
import { Logger } from 'pino';
import { RedisClientType } from 'redis';

let _instance: UserProfileService | null = null;

export function getUserProfileService(): UserProfileService {
  if (!_instance) throw new Error('UserProfileService not initialized');
  return _instance;
}

export function initUserProfileService(
  prisma: PrismaClient,
  redis: RedisClientType | null,
  logger: Logger,
): UserProfileService {
  _instance = new UserProfileService(prisma, redis, logger);
  return _instance;
}

export interface InteractionSignal {
  type: 'message' | 'feedback' | 'tool_use' | 'code_session' | 'flow_execution' | 'copy' | 'regenerate';
  feedbackType?: 'thumbs_up' | 'thumbs_down' | 'copy' | 'regenerate' | 'share' | 'report';
  model?: string;
  toolName?: string;
  format?: string; // code_block, bullet_list, narrative
  topics?: string[];
  language?: string; // programming language
}

export class UserProfileService {
  private logger: Logger;

  constructor(
    private prisma: PrismaClient,
    private redis: RedisClientType | null,
    logger: Logger,
  ) {
    this.logger = logger.child({ service: 'UserProfileService' });
  }

  /**
   * Record a user interaction — lightweight counter updates.
   * Called on every message, feedback, tool use, etc.
   */
  async recordInteraction(userId: string, signal: InteractionSignal): Promise<void> {
    try {
      const profile = await this.getOrCreateProfile(userId);
      const updates: Record<string, any> = {};

      // Always increment interactions
      updates.total_interactions = (profile.total_interactions || 0) + 1;

      // Track active hours
      const currentHour = new Date().getHours();
      const activeHours: number[] = profile.active_hours || [];
      if (!activeHours.includes(currentHour)) {
        updates.active_hours = [...activeHours, currentHour].slice(-24);
      }

      // Handle feedback signals
      if (signal.type === 'feedback' && signal.feedbackType) {
        updates.total_feedback = (profile.total_feedback || 0) + 1;
        const totalFeedback = updates.total_feedback;
        const currentPositive = profile.positive_rate * (profile.total_feedback || 0);

        if (['thumbs_up', 'copy', 'share'].includes(signal.feedbackType)) {
          updates.positive_rate = (currentPositive + 1) / totalFeedback;
        } else if (['thumbs_down', 'regenerate', 'report'].includes(signal.feedbackType)) {
          updates.positive_rate = currentPositive / totalFeedback;
        }

        // Update model preferences
        if (signal.model) {
          const modelPrefs = (profile.model_preferences as Record<string, any>) || {};
          const pref = modelPrefs[signal.model] || { satisfaction: 0.5, sampleSize: 0 };
          pref.sampleSize += 1;
          const isPositive = ['thumbs_up', 'copy', 'share'].includes(signal.feedbackType!);
          // Exponential moving average
          const alpha = 2 / (Math.min(pref.sampleSize, 20) + 1);
          pref.satisfaction = pref.satisfaction * (1 - alpha) + (isPositive ? 1 : 0) * alpha;
          modelPrefs[signal.model] = pref;
          updates.model_preferences = modelPrefs;
        }

        // Update format preference based on feedback
        if (signal.format) {
          if (['thumbs_up', 'copy'].includes(signal.feedbackType)) {
            updates.preferred_format = signal.format;
          }
        }

        // Verbosity inference
        if (signal.feedbackType === 'thumbs_down' && signal.format === 'narrative') {
          updates.verbosity = 'concise';
        }
      }

      // Handle tool usage
      if (signal.type === 'tool_use' && signal.toolName) {
        const affinities = (profile.tool_affinities as Record<string, any>) || {};
        const aff = affinities[signal.toolName] || { count: 0, lastUsed: null };
        aff.count += 1;
        aff.lastUsed = new Date().toISOString();
        affinities[signal.toolName] = aff;
        updates.tool_affinities = affinities;
      }

      // Track programming language usage
      if (signal.language) {
        const languages: string[] = profile.preferred_languages || [];
        if (!languages.includes(signal.language)) {
          updates.preferred_languages = [...languages, signal.language].slice(0, 10);
        }
      }

      // Apply updates
      await (this.prisma as any).userProfile.update({
        where: { user_id: userId },
        data: updates,
      });

      // Invalidate cache
      if (this.redis) {
        this.redis.del(`umem:${userId}:profile`).catch(() => {});
      }

    } catch (err: any) {
      this.logger.debug({ error: err.message, userId, signal: signal.type }, 'recordInteraction failed');
    }
  }

  /**
   * Get user profile, creating if needed
   */
  async getOrCreateProfile(userId: string): Promise<any> {
    try {
      let profile = await (this.prisma as any).userProfile.findUnique({
        where: { user_id: userId },
      });
      if (!profile) {
        profile = await (this.prisma as any).userProfile.create({
          data: { user_id: userId },
        });
      }
      return profile;
    } catch (err: any) {
      this.logger.debug({ error: err.message, userId }, 'getOrCreateProfile failed');
      return {
        user_id: userId,
        verbosity: 'balanced',
        formality: 'balanced',
        technical_depth: 'balanced',
        preferred_format: 'mixed',
        preferred_languages: [],
        domain_expertise: [],
        tool_affinities: {},
        model_preferences: {},
        style_dna: null,
        active_hours: [],
        total_interactions: 0,
        total_feedback: 0,
        positive_rate: 0,
      };
    }
  }

  /**
   * Generate a profile context string for system prompt injection.
   */
  async getProfileContext(userId: string): Promise<string> {
    const profile = await this.getOrCreateProfile(userId);
    if (!profile || profile.total_interactions === 0) return '';

    const lines: string[] = [];

    if (profile.style_dna) {
      return profile.style_dna;
    }

    if (profile.verbosity !== 'balanced') lines.push(`Prefers ${profile.verbosity} responses`);
    if (profile.technical_depth !== 'balanced') lines.push(`Technical depth: ${profile.technical_depth}`);
    if (profile.preferred_format !== 'mixed') {
      const formatMap: Record<string, string> = {
        code_first: 'code examples first, explanations after',
        explanation_first: 'explanations first, then code',
        bullets: 'bullet point format',
      };
      lines.push(`Preferred format: ${formatMap[profile.preferred_format] || profile.preferred_format}`);
    }
    if (profile.preferred_languages?.length > 0) {
      lines.push(`Languages: ${profile.preferred_languages.join(', ')}`);
    }
    if (profile.domain_expertise?.length > 0) {
      lines.push(`Domain expertise: ${profile.domain_expertise.join(', ')}`);
    }

    // Top tools
    const affinities = profile.tool_affinities as Record<string, any> || {};
    const topTools = Object.entries(affinities)
      .sort((a: any, b: any) => (b[1].count || 0) - (a[1].count || 0))
      .slice(0, 5)
      .map(([name]) => name);
    if (topTools.length > 0) {
      lines.push(`Frequently uses: ${topTools.join(', ')}`);
    }

    return lines.length > 0 ? lines.map(l => `- ${l}`).join('\n') : '';
  }
}
