/**
 * OpenAgentic canonical event taxonomy — public exports.
 *
 * This is the contract every service in the platform must speak:
 *   provider stream → ModelStreamEvent (via normalizers)
 *   platform layer  → all other AgenticEvent types (via builders)
 *   downstream UI   → consumes AgenticEvent[]
 */

// Event-builder helpers — typed constructors that stamp `type` + `ts` so
// emit sites never construct event literals by hand. See ./builders.ts.
export {
  buildMessageStart,
  buildContentBlockStart,
  buildContentBlockDelta,
  buildContentBlockStop,
  buildMessageDelta,
  buildMessageStop,
  buildModelPing,
  buildModelError,
  buildStreamStart,
  buildStreamEnd,
  buildDeltaResumeMarker,
  buildToolExecuting,
  buildToolCompleted,
  buildToolFailed,
  buildToolInputDelta,
  buildToolOutputChunk,
  buildToolStatus,
  buildAgentStart,
  buildAgentStep,
  buildAgentStop,
  buildParallelFanoutHeader,
  buildSubAgentStarted,
  buildSubAgentCompleted,
  buildAgentTreeUpdate,
  buildHitlRequest,
  buildHitlResponse,
  buildArtifactStart,
  buildArtifactDelta,
  buildArtifactComplete,
  buildComposeVisual,
  buildComposeApp,
  buildTierHint,
  buildModelHandoffOffer,
  buildVizHead,
  buildToolShortlistChip,
  buildStreamingTable,
  buildDlpBlock,
  buildAuditEvent,
  buildPolicyViolation,
  buildRequestClarification,
  buildCostPulse,
  buildCostRecord,
  buildUsage,
  buildRagCitation,
  buildDocChunk,
  buildMemoryWrite,
  buildEmbeddingIndexed,
  buildVectorProbe,
  buildMcpConnect,
  buildMcpDisconnect,
  buildMcpCapabilityDelta,
  buildUiOpen,
  buildUiPatch,
  buildUiClose,
  buildUiEvent,
  buildKubeEvent,
  buildFilePanelUpdate,
  buildSlashCommandSynthetic,
  buildSessionInfo,
  buildFlowNodeStart,
  buildFlowNodeEnd,
  buildNodeProgress,
  buildFlowCanvasState,
  buildLateSubscriberCatchup,
  buildSessionResume,
  buildReplayPacing,
  buildAgenticCliParity,
  buildPlatformError,
} from './builders.js';

export type {
  // Layer 1 — Model-stream (provider-agnostic)
  MessageStartEvent,
  ContentBlockStartEvent,
  ContentBlockDeltaEvent,
  ContentBlockStopEvent,
  MessageDeltaEvent,
  MessageStopEvent,
  ModelPingEvent,
  ModelErrorEvent,
  ModelStreamEvent,
  StopReason,
  ContentBlock,
  // Layer 2 — stream envelope
  StreamStartEvent,
  StreamEndEvent,
  DeltaResumeMarkerEvent,
  // Layer 3 — tool execution
  ToolExecutingEvent,
  ToolCompletedEvent,
  ToolFailedEvent,
  ToolInputDeltaEvent,
  ToolOutputChunkEvent,
  ToolStatusEvent,
  // Layer 4 — sub-agents
  AgentStartEvent,
  AgentStepEvent,
  AgentStopEvent,
  ParallelFanoutHeaderEvent,
  SubAgentStartedEvent,
  SubAgentCompletedEvent,
  AgentTreeUpdateEvent,
  // Layer 5 — HITL
  HitlRequestEvent,
  HitlResponseEvent,
  // Layer 6 — artifacts
  ArtifactStartEvent,
  ArtifactDeltaEvent,
  ArtifactCompleteEvent,
  ComposeVisualEvent,
  ComposeAppEvent,
  // Layer 7 — viz / handoff
  TierHintEvent,
  ModelHandoffOfferEvent,
  VizHeadEvent,
  ToolShortlistChipEvent,
  StreamingTableEvent,
  // Layer 8 — trust / observability
  DlpBlockEvent,
  AuditEventEvent,
  PolicyViolationEvent,
  RequestClarificationEvent,
  CostPulseEvent,
  CostRecordEvent,
  UsageEvent,
  // Layer 9 — data layers
  RagCitationEvent,
  DocChunkEvent,
  MemoryWriteEvent,
  EmbeddingIndexedEvent,
  VectorProbeEvent,
  // Layer 10 — MCP fabric
  McpConnectEvent,
  McpDisconnectEvent,
  McpCapabilityDeltaEvent,
  // Layer 11 — codemode
  UiOpenEvent,
  UiPatchEvent,
  UiCloseEvent,
  UiEventEvent,
  KubeEventEvent,
  FilePanelUpdateEvent,
  SlashCommandSyntheticEvent,
  SessionInfoEvent,
  // Layer 12 — flows
  FlowNodeStartEvent,
  FlowNodeEndEvent,
  NodeProgressEvent,
  FlowCanvasStateEvent,
  LateSubscriberCatchupEvent,
  // Layer 13 — session durability
  SessionResumeEvent,
  ReplayPacingEvent,
  AgenticCliParityEvent,
  // Layer 14 — platform error
  PlatformErrorEvent,
  // The union
  AgenticEvent,
  AgenticEventType,
} from './types.js';
